version: "3.8"

services:
  backend:
    image: alarm-monitoring-backend:latest

    pull_policy: never

    container_name: alarm-ws-server
    restart: unless-stoped

    ports:
      - "5001:5001" #Webhook Endpoint (HTTP)
      - "5002:5002" #WebSocket Connection

    environment:
      - NODE_ENV=production
