version: "3.8"

services:
  backend:
    image: alarm-monitoring-backend:latest

    container_name: alarm-ws-server
    restart: unless-stopped

    ports:
      - "5001:5001" #Webhook Endpoint (HTTP)
      - "5002:5002" #WebSocket Connection

    volumes: -/app/alarm-monitoring/logs:alarm-ws-server/logs

    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
